### ISSUE TITLE
Print pictures mutliple times

### ISSUE THREAD

**Issue by tensau** [saeugetier/photobooth#84]
A recent wedding showed that a function to print a picture multiple times would be great. The photobooth was used to shoot images for a guestbook, but lots of guests also wanted to have a second printout to keep for themselfes.
Therefore, it would be nice to have an option to print every picture twice.

**Comment by saeugetier** [comment]
Should there be an option to print all pictures twice. Or only single?

**Comment by tensau** [comment]
There should be a possibility to select it when printing so that the user can decide on each photo.
